version: '2'
services:
  backend:
    build: backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
  frontend:
    build: frontend/
    command: npm run start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
