version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  backend:
    build: backend/
    command: bash start.sh
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
  frontend:
    build: frontend/
    command: yarn start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
